### PR TITLE
Update .babelrc

### PR DESCRIPTION
**Pull request by ArtemGovorov**

### CODE REVIEW

**Comment by ArtemGovorov** [comment]
After the change I get the `react not found` error when running wallaby, but if I comment out [this `.babelrc` section](https://github.com/Saeris/Ignition/blob/fcde25457a7e258d0a024ab95b8716948a13efce/.babelrc#L12-L37), then tests start to pass in wallaby ()so the issue is likely somewhere in that section of `.babelrc`.

**Comment by Saeris** [comment]
First of all thanks for the help! Really appreciate it!

So I have a concern about `babel-plugin-transform-export-extensions`, in that it seems Babel has removed that extension (it's no longer part of the babel monorepo). Might not be the best idea to add that dependency if it's possibly been depricated. I haven't been able to confirm that's the case yet though.

Maybe this is the replacement?
https://github.com/babel/babel/tree/master/packages/babel-plugin-syntax-export-extensions

Also for reference all of the tests are going to pass since all I have are placeholders at the moment. I'd have to confirm, but my suspicion is the tests will break again because I'll need the section you highlighted to provide the global modules that my components are using.

You can take a look at another project of mine where I've added AVA/wallaby which has some actual tests which are running and passing: https://github.com/Saeris/Flickr-Wormhole

I don't have the same errors with it because it's not using React/Preact.

I'm new to writing unit tests, so this is the first time I've tried to set up a testing environment, haha.

**Comment by Saeris** [comment]
Looks like `babel-plugin-syntax-export-extensions` isn't a replacement for `babel-plugin-transform-export-extensions`. Given that I don't have export errors in my Flickr-Wormhole project, I'm not sure that's part of the problem.

Seems more likely that it's due to the fact that `react` needs to be aliased to `preact`. Normally you would do this in Webpack according to Preact's documentation:

https://preactjs.com/guide/switching-to-preact

Aliasing in babel isn't in that list, so maybe the approach I've got using [`babel-plugin-webpack-alias`](https://github.com/trayio/babel-plugin-webpack-alias) is flawed.

**Comment by ArtemGovorov** [comment]
This:
```javascript
export Modal from "./modal"
```
requires `babel-plugin-transform-export-extensions`, because this export syntax that you are using is a [stage 1 proposal at the moment](https://github.com/tc39/proposal-export-default-from). See [this](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=KYDwDg9gTgLgBAWQgEwIYBs4DMoQLZwBEAdAPR4oaEBQokscA3nKsskmugDRxTAUA3YBww8YEAOYT0wypgC-2XARKlUAYxgBLCADsAzjTrR4zZMCyoArunip9iOQCVgyK-uBQ4inPiJk-Nw8oGiA&debug=false&circleciRepo=&evaluate=true&lineWrap=false&presets=env&targets=Node-8.6&version=6.26.0) vs. [this](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=KYDwDg9gTgLgBAWQgEwIYBs4DMoQLZwBEAdAPR4oaEBQokscA3nKsskmugDRxTAUA3YBww8YEAOYT0wypgC-2XARKlUAYxgBLCADsAzjTrR4zZMCyoArunip9iOQCVgyK-uBQ4inPiJk-Nw8oGiA&debug=false&circleciRepo=&evaluate=true&lineWrap=false&presets=stage-1%2Cenv&targets=Node-8.6&version=6.26.0).

**Comment by Saeris** [comment]
Well that does bring to my attention that I had part of my config wrong, but I still don't need that plugin. I'm just missing `stage-0` from my test presets, which I've got included in my development and production presets.

I'm working on a fix for the other issue. I'll come back to this in a bit once I've tested that out.

**Comment by ArtemGovorov** [comment]
> but I still don't need that plugin. I'm just missing stage-0 from my test presets

Strictly speaking you still need the plugin, it's just that [`stage-0` includes `stage-1`](https://babeljs.io/docs/plugins/preset-stage-0/) and [this plugin](https://babeljs.io/docs/plugins/preset-stage-1/) with it, but yes, you don't need to include it separately, it'll be applied with the `stage-0` preset.

**Comment by Saeris** [comment]
Fair enough. I'm just trying to be careful of including more plugins in my package.json. I'll have to go through what I already have and cut some out.

It's important to note that I'm using babel 7, so the docs on babel's website are not going to be entirely accurate, and from what I can tell the REPL is still using babel 6 as well.

**Comment by Saeris** [comment]
If you look at the [documentation](https://babeljs.io/docs/plugins/transform-export-extensions/) for `babel-plugin-transform-export-extensions` you'll see at the bottom `Additional export-from statements in ES7` has been withdrawn in favor of two different proposals.

In babel 7 this seems to be split up into these two plugins:

https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-export-default
https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-export-namespace

Export Default is included in the new `stage-1` preset:

https://github.com/babel/babel/blob/master/packages/babel-preset-stage-1/src/index.js

Export Namespace is included in the new `stage-2` preset:

https://github.com/babel/babel/blob/master/packages/babel-preset-stage-2/src/index.js

Just something to be mindful of going forward.

**Comment by Saeris** [comment]
I'm going to close this PR since with your help the solution was found for the issue with wallaby.js

Thanks again for the help @ArtemGovorov! Love the tool you created!

**Pull request closed without merging**
